---
title: "01_trades"
author: "Jolyon Faria"
date: "05/04/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}

# TODO
# Features
# 1. Plot current trades (distribution of values)
# 2. Add configuration
# 3. Plot historical volume
# 4. Change plots to ggplot

# Validation
# 1. Check API using httptest - mock API
# 2. Add tests for trades functions

# Ops
# 1. Automate date
# 2. Add code coverageon on travis

```

```{r, include=FALSE}

# Check API
url_res <- check_cb_api(coinbase_url = "https://api.pro.coinbase.com/products")

```

```{r, include=FALSE}

# Bitcoin distribution
btc_trades <- get_trades_sample() 
btc_trades_all <- combine_trades(btc_trades)
plot_coin(btc_trades_all)
pc_buy(btc_trades_all)
median(btc_trades_all$value)

```

```{r, include=FALSE}

# Algorand distribution
btc_trades <- get_trades_sample(coin_pair = "ALGO-USD") 
btc_trades_all <- combine_trades(btc_trades)
plot_coin(btc_trades_all)
pc_buy(btc_trades_all)
median(btc_trades_all$value)

```

## Appendix

```{r, include=FALSE}
sessionInfo()
```

